<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.pleo.antaeus.core.services.billing.BillingServiceTest" tests="7" skipped="0" failures="0" errors="0" timestamp="2023-12-26T22:35:48" hostname="Szymons-MBP.technicolor.net" time="0.125">
  <properties/>
  <testcase name="should recover with currency conversion when charging invoice with incompatible currency to customer one()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.077"/>
  <testcase name="should fail charging invoice due to payment provider response of insufficient funds()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.012"/>
  <testcase name="should fail charging invoice due to customer not found error()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.009"/>
  <testcase name="should successfully charge invoice()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.006"/>
  <testcase name="should fail charging invoice due to payment provider network error()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.008"/>
  <testcase name="should skip charging not pending invoice()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.006"/>
  <testcase name="should fail charging invoice due to currency mismatch of invoice and customer currency()" classname="io.pleo.antaeus.core.services.billing.BillingServiceTest" time="0.006"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[[Test worker @kotlinx.coroutines.test runner#22] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=134) being processed
[Test worker @kotlinx.coroutines.test runner#22] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice InvoiceId(value=134) successfully charged.
[Test worker @kotlinx.coroutines.test runner#29] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=283) being processed
[Test worker @kotlinx.coroutines.test runner#29] WARN io.pleo.antaeus.core.services.billing.BillingService - Charging invoice with id 283 failed with error InsufficientFunds
[Test worker @kotlinx.coroutines.test runner#36] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=370) being processed
[Test worker @kotlinx.coroutines.test runner#36] WARN io.pleo.antaeus.core.services.billing.BillingService - Charging invoice with id 370 failed with error CustomerNotFound(id=CustomerId(value=634))
[Test worker @kotlinx.coroutines.test runner#43] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=110) being processed
[Test worker @kotlinx.coroutines.test runner#43] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice InvoiceId(value=110) successfully charged.
[Test worker @kotlinx.coroutines.test runner#50] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=110) being processed
[Test worker @kotlinx.coroutines.test runner#50] WARN io.pleo.antaeus.core.services.billing.BillingService - Charging invoice with id 110 failed with error PaymentProviderNetworkError
[Test worker @kotlinx.coroutines.test runner#57] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=889) being processed
[Test worker @kotlinx.coroutines.test runner#57] WARN io.pleo.antaeus.core.services.billing.BillingService - Charging invoice with id 889 failed with error UnknownError
[Test worker @kotlinx.coroutines.test runner#61] INFO io.pleo.antaeus.core.services.billing.BillingService - Invoice with id InvoiceId(value=782) being processed
[Test worker @kotlinx.coroutines.test runner#61] WARN io.pleo.antaeus.core.services.billing.BillingService - Charging invoice with id 782 failed with error CurrencyMismatch
]]></system-err>
</testsuite>
